import express from 'express';
import { randomBytes, createHash, scryptSync, timingSafeEqual } from 'node:crypto';
import { openDatabase, hashPassword } from './database.js';

const digest = v => createHash('sha256').update(v).digest('hex');
const publicUser = u => u ? {id:u.id,name:u.name,email:u.email} : null;
const fail = (status,message) => { const e=new Error(message); e.status=status; throw e; };
const text = (v,name,min=1,max=500) => { if(typeof v!=='string'||v.trim().length<min||v.trim().length>max) fail(400,`Проверьте поле «${name}»`); return v.trim(); };
const integer = (v,name,min,max) => { if(!Number.isInteger(Number(v))||Number(v)<min||Number(v)>max) fail(400,`Проверьте поле «${name}»`); return Number(v); };
const city = v => {if(!['spb','moscow'].includes(v)) fail(400,'Выберите город'); return v;};
const future = v => { const d=new Date(v); if(!Number.isFinite(d.getTime())||d.getTime()<=Date.now()||d.getTime()>Date.now()+366*86400000) fail(400,'Выберите будущую дату в пределах года');return d.toISOString(); };
export function createApp(database) {
  const db=database||openDatabase(); const app=express();
  app.disable('x-powered-by');app.set('trust proxy',1);
  app.use(express.json({limit:'32kb'}));
  app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.get('sec-fetch-site')==='cross-site') return res.status(403).json({error:'Недопустимый источник запроса'});next();});
  app.use('/api',(req,res,next)=>{
    const token=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('kasanie_session='))?.slice(16);
    if(token) req.user=db.prepare('SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>?').get(digest(token),Date.now());
    next();
  });
  const auth=(req,res,next)=>{if(!req.user)return res.status(401).json({error:'Войдите или создайте аккаунт'});next();};
  function session(req,res,user) { const token=randomBytes(32).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(digest(token),user.id,Date.now()+30*86400000);res.cookie('kasanie_session',token,{httpOnly:true,sameSite:'lax',secure:req.secure,maxAge:30*86400000,path:'/'});res.json({user:publicUser(user)}); }
  const attempts=new Map();
  const authLimit=(req,res,next)=>{ const key=req.ip;const entry=attempts.get(key); const now=Date.now(); if(!entry||now-entry.start>15*60*1000)attempts.set(key,{count:1,start:now});else{entry.count++;if(entry.count>30)return res.status(429).json({error:'Слишком много попыток. Повторите через 15 минут.'});}if(attempts.size>10000)for(const [k,v]of attempts)if(now-v.start>15*60*1000)attempts.delete(k);next();};
  app.post('/api/auth/register',authLimit,(req,res)=>{const name=text(req.body.name,'Имя',2,50);const email=text(req.body.email,'Email',5,120).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Введите корректный email');const password=text(req.body.password,'Пароль',8,128);if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'Аккаунт с таким email уже существует');const id=db.prepare('INSERT INTO users(name,email,password) VALUES(?,?,?)').run(name,email,hashPassword(password)).lastInsertRowid;session(req,res,db.prepare('SELECT * FROM users WHERE id=?').get(id));});
  app.post('/api/auth/login',authLimit,(req,res)=>{const email=text(req.body.email,'Email',5,120).toLowerCase();const password=text(req.body.password,'Пароль',1,128);const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);const [salt,hash]=(u?.password||hashPassword('unmatched-password')).split(':');const actual=scryptSync(password,salt,64);if(!u||!timingSafeEqual(Buffer.from(hash,'hex'),actual))fail(401,'Неверный email или пароль');session(req,res,u);});
  app.post('/api/auth/logout',(req,res)=>{const token=req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('kasanie_session='))?.slice(16);if(token)db.prepare('DELETE FROM sessions WHERE token=?').run(digest(token));res.clearCookie('kasanie_session',{path:'/'}).json({ok:true});});
  app.get('/api/me',(req,res)=>res.json({user:publicUser(req.user)}));
  app.get('/api/catalog',(req,res)=>{
    const uid=req.user?.id||0;
    const pitches=db.prepare(`SELECT p.*,COALESCE((SELECT ROUND(AVG(rating),1) FROM reviews WHERE pitch_id=p.id),0) AS rating,(SELECT COUNT(*) FROM reviews WHERE pitch_id=p.id) AS review_count,EXISTS(SELECT 1 FROM favorites WHERE pitch_id=p.id AND user_id=?) AS favorite FROM pitches p ORDER BY p.id`).all(uid);
    const games=db.prepare(`SELECT g.*,p.name AS pitch_name,p.city,p.address,p.district,u.name AS owner_name,(SELECT COALESCE(SUM(seats),0) FROM game_members WHERE game_id=g.id) AS occupied,EXISTS(SELECT 1 FROM game_members WHERE game_id=g.id AND user_id=?) AS joined FROM games g JOIN pitches p ON p.id=g.pitch_id JOIN users u ON u.id=g.owner_id WHERE g.starts_at>? ORDER BY g.starts_at`).all(uid,new Date().toISOString());
    const trips=db.prepare(`SELECT t.*,u.name AS owner_name,(SELECT COALESCE(SUM(seats),0) FROM trip_members WHERE trip_id=t.id) AS occupied,EXISTS(SELECT 1 FROM trip_members WHERE trip_id=t.id AND user_id=?) AS joined FROM trips t JOIN users u ON u.id=t.owner_id WHERE t.starts_at>? ORDER BY t.starts_at`).all(uid,new Date().toISOString());
    res.json({pitches,games,trips,user:publicUser(req.user)});
  });
  app.post('/api/pitches',auth,(req,res)=>{const b=req.body;const name=text(b.name,'Название',3,100), c=city(b.city),address=text(b.address,'Адрес',5,180),district=text(b.district,'Район',2,80);if(!['Искусственный газон','Натуральный газон','Резиновое покрытие','Грунт'].includes(b.surface))fail(400,'Выберите покрытие');if(!['5 × 5','7 × 7','11 × 11'].includes(b.format))fail(400,'Выберите формат');const lat=Number(b.lat),lng=Number(b.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)fail(400,'Укажите корректные координаты');const id=db.prepare('INSERT INTO pitches(name,city,address,district,surface,format,price,lighting,changing_room,parking,lat,lng,description,owner_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(name,c,address,district,b.surface,b.format,integer(b.price,'Цена',0,50000),b.lighting?1:0,b.changing_room?1:0,b.parking?1:0,lat,lng,text(b.description,'Описание',10,2000),req.user.id).lastInsertRowid;res.status(201).json({id:Number(id)});});
  app.get('/api/pitches/:id/reviews',(req,res)=>res.json({reviews:db.prepare('SELECT r.*,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE pitch_id=? ORDER BY r.created_at DESC,r.id DESC').all(req.params.id)}));
  app.post('/api/pitches/:id/reviews',auth,(req,res)=>{if(!db.prepare('SELECT id FROM pitches WHERE id=?').get(req.params.id))fail(404,'Поле не найдено');db.prepare('INSERT INTO reviews(pitch_id,user_id,rating,text) VALUES(?,?,?,?) ON CONFLICT(pitch_id,user_id) DO UPDATE SET rating=excluded.rating,text=excluded.text,created_at=CURRENT_TIMESTAMP').run(req.params.id,req.user.id,integer(req.body.rating,'Оценка',1,5),text(req.body.text,'Отзыв',5,1000));res.json({ok:true});});
  app.post('/api/pitches/:id/favorite',auth,(req,res)=>{if(!db.prepare('SELECT id FROM pitches WHERE id=?').get(req.params.id))fail(404,'Поле не найдено');const exists=db.prepare('SELECT 1 FROM favorites WHERE pitch_id=? AND user_id=?').get(req.params.id,req.user.id);if(exists)db.prepare('DELETE FROM favorites WHERE pitch_id=? AND user_id=?').run(req.params.id,req.user.id);else db.prepare('INSERT INTO favorites VALUES(?,?)').run(req.params.id,req.user.id);res.json({favorite:!exists});});
  app.post('/api/games',auth,(req,res)=>{const b=req.body;if(!db.prepare('SELECT id FROM pitches WHERE id=?').get(b.pitch_id))fail(400,'Выберите поле');const capacity=integer(b.capacity,'Всего игроков',2,30),seats=integer(b.seats,'Ваша группа',1,capacity);if(!['Любой уровень','Начинающий','Средний','Опытный'].includes(b.level))fail(400,'Выберите уровень');const id=db.prepare('INSERT INTO games(pitch_id,owner_id,title,starts_at,duration,capacity,level,price,description) VALUES(?,?,?,?,?,?,?,?,?)').run(b.pitch_id,req.user.id,text(b.title,'Название игры',3,100),future(b.starts_at),integer(b.duration,'Длительность',30,240),capacity,b.level,integer(b.price,'Взнос',0,10000),text(b.description,'Описание',5,2000)).lastInsertRowid;db.prepare('INSERT INTO game_members VALUES(?,?,?)').run(id,req.user.id,seats);res.status(201).json({id:Number(id)});});
  app.post('/api/trips',auth,(req,res)=>{const b=req.body;const cap=integer(b.capacity,'Всего участников',2,30),seats=integer(b.seats,'Ваша группа',1,cap);const id=db.prepare('INSERT INTO trips(owner_id,title,destination,city,starts_at,capacity,price,description) VALUES(?,?,?,?,?,?,?,?)').run(req.user.id,text(b.title,'Название',3,100),text(b.destination,'Куда едем',3,150),city(b.city),future(b.starts_at),cap,integer(b.price,'Стоимость',0,50000),text(b.description,'План поездки',10,2000)).lastInsertRowid;db.prepare('INSERT INTO trip_members VALUES(?,?,?)').run(id,req.user.id,seats);res.status(201).json({id:Number(id)});});
  for(const type of ['games','trips']){
    const member=type==='games'?'game_members':'trip_members', fk=type==='games'?'game_id':'trip_id';
    app.get(`/api/${type}/:id/members`,(req,res)=>res.json({members:db.prepare(`SELECT m.seats,u.id,u.name FROM ${member} m JOIN users u ON u.id=m.user_id WHERE ${fk}=?`).all(req.params.id)}));
    app.post(`/api/${type}/:id/join`,auth,(req,res)=>{const item=db.prepare(`SELECT * FROM ${type} WHERE id=?`).get(req.params.id);if(!item)fail(404,'Встреча не найдена');if(new Date(item.starts_at).getTime()<=Date.now())fail(400,'Встреча уже началась');if(db.prepare(`SELECT 1 FROM ${member} WHERE ${fk}=? AND user_id=?`).get(item.id,req.user.id))fail(409,'Вы уже участвуете');const seats=integer(req.body.seats||1,'Количество игроков',1,30);const occupied=db.prepare(`SELECT COALESCE(SUM(seats),0) AS n FROM ${member} WHERE ${fk}=?`).get(item.id).n;if(occupied+seats>item.capacity)fail(409,'Недостаточно свободных мест');db.prepare(`INSERT INTO ${member} VALUES(?,?,?)`).run(item.id,req.user.id,seats);res.json({ok:true});});
    app.post(`/api/${type}/:id/leave`,auth,(req,res)=>{const item=db.prepare(`SELECT * FROM ${type} WHERE id=?`).get(req.params.id);if(!item)fail(404,'Встреча не найдена');if(item.owner_id===req.user.id)fail(400,'Организатор может отменить встречу');db.prepare(`DELETE FROM ${member} WHERE ${fk}=? AND user_id=?`).run(item.id,req.user.id);res.json({ok:true});});
    app.delete(`/api/${type}/:id`,auth,(req,res)=>{const item=db.prepare(`SELECT * FROM ${type} WHERE id=?`).get(req.params.id);if(!item)fail(404,'Встреча не найдена');if(item.owner_id!==req.user.id)fail(403,'Отменить встречу может только организатор');db.prepare(`DELETE FROM ${type} WHERE id=?`).run(item.id);res.json({ok:true});});
  }
  app.get('/api/health',(req,res)=>res.json({ok:true,pitches:db.prepare('SELECT COUNT(*) AS n FROM pitches').get().n}));
  app.use('/api',(req,res)=>res.status(404).json({error:'Запрос не найден'}));
  app.use((err,req,res,next)=>{if(res.headersSent)return next(err); if(!err.status)console.error(err);res.status(err.status||500).json({error:err.status?err.message:'Не удалось выполнить запрос. Попробуйте ещё раз.'});});
  return app;
}
